version: '3'

services:
  apis:
    build: .
    restart: always
    ports:
      - "4848:4848"
      - "8080:8080"
    networks:
      synchronicity:
        aliases:
          - apis.docker
    volumes:
      - ./apis-config:/etc/default/tmf/
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_HOST=mysql

networks:
  synchronicity:
    external: true
